name: Build e Deploy iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar versão do Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Instalar chave API do App Store Connect
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "${{ secrets.APP_STORE_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_KEY_ID }}.p8

      - name: Criar Keychain Temporária
        run: |
          KEYCHAIN_PATH=$HOME/Library/Keychains/build.keychain-db
          security create-keychain -p "" $KEYCHAIN_PATH
          security set-keychain-settings -lut 3600 $KEYCHAIN_PATH
          security unlock-keychain -p "" $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH

      - name: Criar ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>destination</key>
              <string>upload</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>W5399G3VHK</string>
          </dict>
          EOF

      - name: Instalar Dependências CocoaPods
        run: |
          pod repo update
          pod install --repo-update

      - name: Compilar e Gerar Archive
        run: |
          xcodebuild archive \
                     -workspace "Moda Acessível.xcworkspace" \
                     -scheme "Moda Acessível" \
                     -destination "generic/platform=iOS" \
                     -configuration Release \
                     -archivePath $PWD/build/ModaAcessivel.xcarchive \
                     DEVELOPMENT_TEAM=W5399G3VHK \
                     CODE_SIGN_STYLE=Automatic \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     -allowProvisioningUpdates \
                     -authenticationKeyID ${{ secrets.APP_STORE_KEY_ID }} \
                     -authenticationKeyIssuerID ${{ secrets.APP_STORE_ISSUER_ID }} \
                     -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_KEY_ID }}.p8

      - name: Exportar e Assinar IPA para App Store
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/ModaAcessivel.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD/build/out \
                     -allowProvisioningUpdates \
                     -authenticationKeyID ${{ secrets.APP_STORE_KEY_ID }} \
                     -authenticationKeyIssuerID ${{ secrets.APP_STORE_ISSUER_ID }} \
                     -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APP_STORE_KEY_ID }}.p8

      - name: Upload para App Store Connect
        run: |
          xcrun altool --upload-app \
                       --type ios \
                       --file $PWD/build/out/*.ipa \
                       --apiKey ${{ secrets.APP_STORE_KEY_ID }} \
                       --apiIssuer ${{ secrets.APP_STORE_ISSUER_ID }}
